### PR TITLE
Changed favicon

### PR DESCRIPTION
**Pull request by martispyc**

### CODE REVIEW

**Comment by thekingslee** [comment]
Great job @martispyc , I will go ahead to close the issue.

**Comment by thekingslee** [comment]
Do you have any experience with Auth0?

**Comment by martispyc** [comment]
> Do you have any experience with Auth0?

Sadly, no

**Comment by thekingslee** [comment]
> 

okay

**Comment by thekingslee** [comment]
Let's connect on Twitter, I am considering creating a community around this project. This is me https://twitter.com/nworiekingslee

**Comment by martispyc** [comment]
> Let's connect on Twitter, I am considering creating a community around this project. This is me [twitter.com/nworiekingslee](https://twitter.com/nworiekingslee)

Sure! 
https://twitter.com/martispyc

**Pull request merged**
